---
  - name: Install EPAL
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Install firewalld
    yum:
      name: firewalld
      state: present

  - name: firewalld service state
    service:
      name: firewalld
      state: started
      enabled: true

  - name: Copy nginx configuration
    template:
      src: default.j2
      dest: /etc/nginx/conf.d/default.conf
    notify: restart nginx service

  - name: insert firewalld rule for nginx
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
    ignore_errors: yes

  - name: nginx service state
    service:
      name: nginx
      state: started
      enabled: true